# Generated by Django 3.1.3 on 2021-01-23 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone_num', models.CharField(max_length=15)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_one', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('job_position_one', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posision')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion del puesto')),
                ('year', models.PositiveIntegerField(default=0)),
                ('departure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de la salida')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpLab.employee')),
            ],
        ),
    ]
