# Generated by Django 3.1.3 on 2021-01-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone_num', models.CharField(max_length=15)),
                ('years_of_cursed', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('career', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_university', models.TextField(blank=True, max_length=100, null=True)),
                ('year_of_study', models.PositiveIntegerField(default=0)),
                ('description_study_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion de la carrera')),
                ('average', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.student')),
            ],
        ),
    ]
